# Generated by Django 5.1.6 on 2025-02-27 11:20

import core.fields.identifier
import core.models.base
import django.db.models.deletion
import django.utils.timezone
import library.modelutils.fields
import library.simplehistory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            "DROP EXTENSION IF EXISTS pg_trgm;"
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nama kategori menu, harus unik.', max_length=255, unique=True, verbose_name='Nama Kategori')),
                ('order', models.IntegerField(default=0, help_text='Urutan tampilan kategori dalam sidebar.', verbose_name='Urutan')),
            ],
            options={
                'verbose_name': 'Used store menu category',
                'db_table': '"core"."menu_category"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistoricalSequence',
            fields=[
                ('created', library.modelutils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', library.modelutils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('read_only', models.BooleanField(default=False, help_text='Used for disable modification', verbose_name='read only')),
                ('enable', models.BooleanField(default=False, help_text='Used for usable', verbose_name='enable')),
                ('properties', models.JSONField(default=dict, help_text='Used for other field value', verbose_name='properties')),
                ('description', models.TextField(blank=True, help_text='Used for remark', null=True, verbose_name='description')),
                ('sequence_id', core.fields.identifier.ShortUUIDField(alphabet=None, db_index=True, help_text='Used for identity', length=25, max_length=25, prefix='', verbose_name='sequence id')),
                ('part', models.CharField(help_text='Used for identity part', verbose_name='part')),
                ('length', models.IntegerField(blank=True, help_text='Used for length character number', null=True, verbose_name='length')),
                ('prefix', models.CharField(blank=True, help_text='Used for prefix number', null=True, verbose_name='prefix')),
                ('suffix', models.CharField(blank=True, help_text='Used for suffix number', null=True, verbose_name='suffix')),
                ('repeater', models.CharField(blank=True, help_text='Used for repeater character before after prefix before current number', null=True, verbose_name='repeater')),
                ('counter', models.IntegerField(blank=True, help_text='Used for increment', null=True, verbose_name='counter')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('content_type', models.ForeignKey(blank=True, db_constraint=False, help_text='Used for linked key model comment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype', verbose_name='content type')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Used store history sequence',
                'verbose_name_plural': 'historical Used store sequence auto numberings',
                'db_table': '"history"."core_sequence"',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(library.simplehistory.models.HistoricalChanges, core.models.base.BaseStatus, models.Model),
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('created', library.modelutils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', library.modelutils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('read_only', models.BooleanField(default=False, help_text='Used for disable modification', verbose_name='read only')),
                ('enable', models.BooleanField(default=False, help_text='Used for usable', verbose_name='enable')),
                ('properties', models.JSONField(default=dict, help_text='Used for other field value', verbose_name='properties')),
                ('description', models.TextField(blank=True, help_text='Used for remark', null=True, verbose_name='description')),
                ('sequence_id', core.fields.identifier.ShortUUIDField(alphabet=None, help_text='Used for identity', length=25, max_length=25, prefix='', primary_key=True, serialize=False, verbose_name='sequence id')),
                ('part', models.CharField(help_text='Used for identity part', verbose_name='part')),
                ('length', models.IntegerField(blank=True, help_text='Used for length character number', null=True, verbose_name='length')),
                ('prefix', models.CharField(blank=True, help_text='Used for prefix number', null=True, verbose_name='prefix')),
                ('suffix', models.CharField(blank=True, help_text='Used for suffix number', null=True, verbose_name='suffix')),
                ('repeater', models.CharField(blank=True, help_text='Used for repeater character before after prefix before current number', null=True, verbose_name='repeater')),
                ('counter', models.IntegerField(blank=True, help_text='Used for increment', null=True, verbose_name='counter')),
                ('content_type', models.ForeignKey(help_text='Used for linked key model comment', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
            ],
            options={
                'verbose_name': 'Used store sequence auto numbering',
                'db_table': '"core"."sequence"',
                'managed': True,
            },
            bases=(core.models.base.BaseStatus, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSequenceNumber',
            fields=[
                ('created', library.modelutils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('id', core.fields.identifier.ShortUUIDField(alphabet=None, db_index=True, help_text='Used for identity', length=25, max_length=25, prefix='', verbose_name='sequence data id')),
                ('part', models.CharField(help_text='Used for identity part', verbose_name='part')),
                ('number', models.CharField(blank=True, null=True, verbose_name='number')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, help_text='Used for linked key owner number', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('sequence', models.ForeignKey(blank=True, db_constraint=False, help_text='Used for linked key', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.sequence', verbose_name='sequence')),
            ],
            options={
                'verbose_name': 'Used store history sequence number',
                'verbose_name_plural': 'historical Used store sequence auto numbering current numbers',
                'db_table': '"history"."core_sequence_number"',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(library.simplehistory.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSequenceData',
            fields=[
                ('created', library.modelutils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('id', core.fields.identifier.ShortUUIDField(alphabet=None, db_index=True, help_text='Used for identity', length=25, max_length=25, prefix='', verbose_name='sequence data id')),
                ('part', models.CharField(help_text='Used for identity part', verbose_name='part')),
                ('current', models.IntegerField(blank=True, null=True, verbose_name='current')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sequence', models.ForeignKey(blank=True, db_constraint=False, help_text='Used for linked key', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.sequence', verbose_name='sequence')),
            ],
            options={
                'verbose_name': 'Used store history sequence data',
                'verbose_name_plural': 'historical Used store sequence auto numbering data after formateds',
                'db_table': '"history"."core_sequence_data"',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(library.simplehistory.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Nama menu yang akan ditampilkan di sidebar.', max_length=255, unique=True, verbose_name='Judul Menu')),
                ('icon', models.CharField(blank=True, help_text="Class ikon untuk menu (contoh: 'ri-home-8-line').", max_length=100, null=True, verbose_name='Ikon')),
                ('url', models.CharField(blank=True, help_text='URL tujuan menu. Kosongkan jika hanya sebagai kategori.', max_length=255, null=True, verbose_name='URL')),
                ('order', models.IntegerField(default=0, help_text='Urutan tampilan menu dalam kategori atau submenu.', verbose_name='Urutan')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent menu jika ini adalah submenu.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='core.menu', verbose_name='Menu Induk')),
                ('category', models.ForeignKey(blank=True, help_text='Kategori utama menu ini.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='core.menucategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Used store menu',
                'db_table': '"core"."menu"',
                'ordering': ['category__order', 'order'],
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('title', 'parent'), name='unique_menu_per_parent')],
            },
        ),
        migrations.CreateModel(
            name='SequenceData',
            fields=[
                ('created', library.modelutils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', library.modelutils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', core.fields.identifier.ShortUUIDField(alphabet=None, help_text='Used for identity', length=25, max_length=25, prefix='', primary_key=True, serialize=False, verbose_name='sequence data id')),
                ('part', models.CharField(help_text='Used for identity part', verbose_name='part')),
                ('current', models.IntegerField(blank=True, null=True, verbose_name='current')),
                ('sequence', models.ForeignKey(help_text='Used for linked key', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s', to='core.sequence', verbose_name='sequence')),
            ],
            options={
                'verbose_name': 'Used store sequence auto numbering data after formated',
                'db_table': '"core"."sequence_data"',
                'managed': True,
                'unique_together': {('sequence', 'part')},
            },
        ),
        migrations.CreateModel(
            name='SequenceNumber',
            fields=[
                ('created', library.modelutils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', library.modelutils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', core.fields.identifier.ShortUUIDField(alphabet=None, help_text='Used for identity', length=25, max_length=25, prefix='', primary_key=True, serialize=False, verbose_name='sequence data id')),
                ('part', models.CharField(help_text='Used for identity part', verbose_name='part')),
                ('number', models.CharField(blank=True, null=True, verbose_name='number')),
                ('owner', models.ForeignKey(blank=True, help_text='Used for linked key owner number', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('sequence', models.ForeignKey(help_text='Used for linked key', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s', to='core.sequence', verbose_name='sequence')),
            ],
            options={
                'verbose_name': 'Used store sequence auto numbering current number',
                'db_table': '"core"."sequence_number"',
                'managed': True,
                'unique_together': {('sequence', 'part', 'owner')},
            },
        ),
    ]
