# Generated by Django 5.1.6 on 2025-02-27 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nama kategori menu, harus unik.', max_length=255, unique=True, verbose_name='Nama Kategori')),
                ('order', models.IntegerField(default=0, help_text='Urutan tampilan kategori dalam sidebar.', verbose_name='Urutan')),
            ],
            options={
                'verbose_name': 'Used store menu category',
                'db_table': '"core"."menu_category"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Nama menu yang akan ditampilkan di sidebar.', max_length=255, unique=True, verbose_name='Judul Menu')),
                ('icon', models.CharField(blank=True, help_text="Class ikon untuk menu (contoh: 'ri-home-8-line').", max_length=100, null=True, verbose_name='Ikon')),
                ('url', models.CharField(blank=True, help_text='URL tujuan menu. Kosongkan jika hanya sebagai kategori.', max_length=255, null=True, verbose_name='URL')),
                ('order', models.IntegerField(default=0, help_text='Urutan tampilan menu dalam kategori atau submenu.', verbose_name='Urutan')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent menu jika ini adalah submenu.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='core.menu', verbose_name='Menu Induk')),
                ('category', models.ForeignKey(blank=True, help_text='Kategori utama menu ini.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='core.menucategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Used store menu',
                'db_table': '"core"."menu"',
                'ordering': ['category__order', 'order'],
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('title', 'parent'), name='unique_menu_per_parent')],
            },
        ),
    ]
