# Generated by Django 5.1.6 on 2025-03-17 04:48

import core.models.base
import django.db.models.deletion
import django.utils.timezone
import library.modelutils.fields
import library.simplehistory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('created', library.modelutils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', library.modelutils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('read_only', models.BooleanField(default=False, help_text='Used for disable modification', verbose_name='read only')),
                ('enable', models.BooleanField(default=False, help_text='Used for usable', verbose_name='enable')),
                ('properties', models.JSONField(default=dict, help_text='Used for other field value', verbose_name='properties')),
                ('description', models.TextField(blank=True, help_text='Used for remark', null=True, verbose_name='description')),
                ('area_id', models.TextField(help_text='used for area id', primary_key=True, serialize=False, verbose_name='area id')),
                ('area_name', models.TextField(help_text='used for area name', verbose_name='area name')),
                ('status', models.CharField(default='draft', help_text='Used for status', verbose_name='status')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent area jika ini adalah area detail.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areadetail', to='master.area', verbose_name='Area')),
            ],
            options={
                'verbose_name': 'Used store area',
                'db_table': '"master"."area"',
                'managed': True,
            },
            bases=(core.models.base.BaseStatus, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalArea',
            fields=[
                ('created', library.modelutils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', library.modelutils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('read_only', models.BooleanField(default=False, help_text='Used for disable modification', verbose_name='read only')),
                ('enable', models.BooleanField(default=False, help_text='Used for usable', verbose_name='enable')),
                ('properties', models.JSONField(default=dict, help_text='Used for other field value', verbose_name='properties')),
                ('description', models.TextField(blank=True, help_text='Used for remark', null=True, verbose_name='description')),
                ('area_id', models.TextField(db_index=True, help_text='used for area id', verbose_name='area id')),
                ('area_name', models.TextField(help_text='used for area name', verbose_name='area name')),
                ('status', models.CharField(default='draft', help_text='Used for status', verbose_name='status')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, help_text='Parent area jika ini adalah area detail.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='master.area', verbose_name='Area')),
            ],
            options={
                'verbose_name': 'Area store history area',
                'verbose_name_plural': 'historical Used store areas',
                'db_table': '"history"."master_area"',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(library.simplehistory.models.HistoricalChanges, core.models.base.BaseStatus, models.Model),
        ),
    ]
