# Generated by Django 5.1.6 on 2025-02-27 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(help_text='Used for identity for signin', primary_key=True, serialize=False, verbose_name='user id')),
                ('user_name', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. This column is an alternative identity.', max_length=150, unique=True, verbose_name='user name')),
                ('real_name', models.CharField(help_text='Used for display purposes', max_length=255, verbose_name='real name')),
                ('email', models.EmailField(blank=True, help_text='Used for email and alternative identity', max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, help_text='Used for phone and alternative identity', max_length=15, null=True, unique=True, verbose_name='phone')),
                ('password', models.CharField(help_text='Used to store password', max_length=255, verbose_name='password')),
                ('avatar', models.CharField(blank=True, help_text='Used for profile picture', max_length=255, null=True, verbose_name='avatar')),
                ('actived_date', models.DateTimeField(blank=True, help_text='Used for tracking activation date', null=True, verbose_name='activated date')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now, help_text='Used for tracking join date', verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'Used store user',
                'db_table': '"authentication"."user"',
                'managed': True,
            },
        ),
    ]
