# Generated by Django 5.1.6 on 2025-03-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': '"auth_group_permissions"',
                'managed': False,
            },
        ),
        migrations.RenameModel(
            old_name='HistoricalGroups',
            new_name='HistoricalGroup',
        ),
        migrations.DeleteModel(
            name='GroupsPermission',
        ),
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
    ]
