# Generated by Django 5.1.6 on 2025-03-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_grouppermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_hierarchy',
            field=models.CharField(blank=True, help_text='Used for hierarchy group', null=True, verbose_name='group hierarchy'),
        ),
        migrations.AddField(
            model_name='historicalgroup',
            name='group_hierarchy',
            field=models.CharField(blank=True, help_text='Used for hierarchy group', null=True, verbose_name='group hierarchy'),
        ),
    ]
